Ishu Suggestions to Instructions
sabre1041/iot-ocp pull request #12
Opened 2016-11-03 21:24 UTC by ishuverma

Still working on some of the images but wanted to do the first PR so you can start looking at what I've so far

2016-11-06 21:19 UTC, sabre1041 requested changes
Really good writeup! A couple small changes and it should be good to go

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +* https://access.redhat.com/documentation/en/red-hat-xpaas/version-0/red-hat-xpaas-fuse-integration-services-image/[Fuse Integration Services]*
Replace \* with - in bullet point

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +* Simulated Software Sensor - Need a description
Idea for a description: Spring boot based software sensor for simulating metrics

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +* OpenShift Command Line Interface (CLI) - Do we still need this?
The CLI is needs to be installed wherever the `init.sh` script is launched from

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +*Step 4:* Login to the OpenShift web console using a web browser at 10.1.2.2:5443 (login/password - admin/admin) and select the **iot-ose** project
This assumes that you are using the CDK. I would genericize to be "Launch the OpenShift web console and login..."

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +image:/images/OSE-projects.png[width="500", height="400", align="center"]
Images are not appearing. Overview diagram is though

2016-11-06 21:19 UTC, sabre1041 commented on README.adoc
> +The init script triggers asynchronous builds and deployments of A-MQ, Decision Server, Fuse Integration Service, PostgreSQL, Zeppelin and Software Sensor components. OpenShift web console provides a
init script now tracks the builds synchronously. Can you update?

2016-11-07 03:17 UTC, ishuverma commented on README.adoc
> +* https://access.redhat.com/documentation/en/red-hat-xpaas/version-0/red-hat-xpaas-fuse-integration-services-image/[Fuse Integration Services]*
done

2016-11-07 03:19 UTC, ishuverma commented on README.adoc
> +* Simulated Software Sensor - Need a description
I was thinking of description of what the sensor does: generates temp, gps and vibration data to simulate the movement of a package on a truck. 
I can write this up and you can review to see if it makes sense

2016-11-07 03:20 UTC, ishuverma commented on README.adoc
> +* OpenShift Command Line Interface (CLI) - Do we still need this?
ok

2016-11-07 03:21 UTC, ishuverma commented on README.adoc
> +The init script triggers asynchronous builds and deployments of A-MQ, Decision Server, Fuse Integration Service, PostgreSQL, Zeppelin and Software Sensor components. OpenShift web console provides a
done

2016-11-07 03:23 UTC, ishuverma commented on README.adoc
> +*Step 4:* Login to the OpenShift web console using a web browser at 10.1.2.2:5443 (login/password - admin/admin) and select the **iot-ose** project
to clarify, should I delete: 
"using a web browser" 
or
"using web browser at using a web browser10.1.2.2:5443"

2016-11-07 03:25 UTC, ishuverma commented on README.adoc
> +image:/images/OSE-projects.png[width="500", height="400", align="center"]
none of the images are appearing? 

I see them on my branch though? I wonder if they made it through the PR

2016-11-07 05:43 UTC, sabre1041 commented on README.adoc
> +*Step 4:* Login to the OpenShift web console using a web browser at 10.1.2.2:5443 (login/password - admin/admin) and select the **iot-ose** project
I would remove the reference to 10.1.2.2:8443

2016-11-07 05:45 UTC, sabre1041 commented on README.adoc
> +image:/images/OSE-projects.png[width="500", height="400", align="center"]
The images are part of the PR, but they are not showing up on the README.adoc. The image that is appearing uses the syntax starting with `image::images` denoting a relative path vs  `image:/images` which is not working

2016-11-07 16:16 UTC, ishuverma commented on README.adoc
> +image:/images/OSE-projects.png[width="500", height="400", align="center"]
updated the path for rest of the images. Let me know if it worked

2016-11-15 03:47 UTC, sabre1041 commented on README.adoc
> +image:/images/Zeppelin-service.png[width="500", height="400", align="center"]
This image is not correctly linked

2016-11-15 03:59 UTC, sabre1041 commented on README.adoc
> +*Step 4:* Login to the OpenShift web console using a web browser at 10.1.2.2:5443 (login/password - admin/admin) and select the **iot-ose** project
Still need to remove `10.1.2.2` addresses to genercize

2016-11-15 04:21 UTC, sabre1041 approved these changes

2016-11-15 04:22 UTC, merged