First iteration of the documentation
sabre1041/iot-ocp pull request #2
Opened 2016-10-06 01:12 UTC by ishuverma

2016-10-07 03:52 UTC, sabre1041 requested changes
Love the diagram and the move to .adoc format

It appears you are missing the most recent version of the README that includes how to set up Zeppelin. Would you be able to integrate those changes in?

2016-10-07 03:52 UTC, sabre1041 commented on README.adoc
> +* [Fuse Integration Services](https://access.redhat.com/documentation/en/red-hat-xpaas/version-0/red-hat-xpaas-fuse-integration-services-image/)
Links are not in asciidoc format

2016-10-07 03:52 UTC, sabre1041 commented on README.adoc
> +image:images/ose-iot.png[]
Do we want to denote these are not full instances of BRMS and Fuse and instead xPaaS?

2016-10-07 05:35 UTC, ishuverma commented
Yes, I noticed the changes yesterday midway. I'll rebase to the new rev and
create a new pull request.

I've lot of other screenshots and stuff I want to add.

ishu

On Thu, Oct 6, 2016 at 8:52 PM, Andrew Block <notifications@github.com>
wrote:

> *@sabre1041* requested changes on this pull request.
>
> Love the diagram and the move to .adoc format
>
> It appears you are missing the most recent version of the README that
> includes how to set up Zeppelin. Would you be able to integrate those
> changes in?
> ------------------------------
>
> In README.adoc
> <https://github.com/sabre1041/iot-ose/pull/2#pullrequestreview-3241490>:
>
> > +:Date:      10/10/2016
> +
> +== Overview
> +Demonstration of Intelligent IoT Gateway on the Red Hat OpenShift Container Platform. The Gateway enables IoT data transformation, routing and real time decision-making at the edge. OpenShift provides secure enterprise-grade container platform to accelerate IoT application delivery. Each component of the demo runs in its own container, thereby, allowing security, scalability and ease of deployment.
> +
> +image:images/ose-iot.png[]
> +
> +This demo uses the CDK platform: learn how to install CDK https://github.com/redhatdemocentral/cdk-install-demo[here]
> +
> +*Please note: This repository is currently under development and the feature set/components are subject to change without notice*
> +
> +== Components
> +
> +* [AMQ and MQTT](https://access.redhat.com/documentation/en/red-hat-xpaas/0/paged/red-hat-xpaas-a-mq-image/)
> +* [Realtime Decision Server](https://access.redhat.com/documentation/en/red-hat-xpaas/0/paged/red-hat-xpaas-a-mq-image/)
> +* [Fuse Integration Services](https://access.redhat.com/documentation/en/red-hat-xpaas/version-0/red-hat-xpaas-fuse-integration-services-image/)
>
> Links are not in asciidoc format
> ------------------------------
>
> In README.adoc
> <https://github.com/sabre1041/iot-ose/pull/2#pullrequestreview-3241490>:
>
> > @@ -0,0 +1,61 @@
> += IoT OpenShift Demo
> +
> +:Author:    Andrew Block, Ishu Verma
> +:Email:     ablock@redhat.com, iverma@redhat.com
> +:Date:      10/10/2016
> +
> +== Overview
> +Demonstration of Intelligent IoT Gateway on the Red Hat OpenShift Container Platform. The Gateway enables IoT data transformation, routing and real time decision-making at the edge. OpenShift provides secure enterprise-grade container platform to accelerate IoT application delivery. Each component of the demo runs in its own container, thereby, allowing security, scalability and ease of deployment.
> +
> +image:images/ose-iot.png[]
>
> Do we want to denote these are not full instances of BRMS and Fuse and
> instead xPaaS?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sabre1041/iot-ose/pull/2#pullrequestreview-3241490>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APpY8N9b9RsdPeOERXMWxDxgF56RVX3cks5qxcH1gaJpZM4KPcy5>
> .
>

2016-10-11 22:18 UTC, closed without merging

2016-10-11 22:18 UTC, ishuverma commented
sent another request based on the latest rev of readme