Updated Readme and separated Zeppelin setup to another page
sabre1041/iot-ocp pull request #5
Opened 2016-10-12 20:49 UTC by ishuverma

2016-10-24 03:20 UTC, sabre1041 requested changes
Added a few comments. The latest PR and enhancements to Zeppelin will require modifications to some of the instructions. 

Great start! Let's discuss how to integrate both of these changes

2016-10-24 03:20 UTC, sabre1041 commented on README.adoc
> +* [AMQ and MQTT](https://access.redhat.com/documentation/en/red-hat-xpaas/0/paged/red-hat-xpaas-a-mq-image/)
These links are markdown syntax instead of asciidoc

2016-10-24 03:20 UTC, sabre1041 commented on README.adoc
> +image:images/ose-iot.png[width="500", height="400", align="center"]
Awesome photo. Can we include A-MQ as the recipient of the messages and fuse reading from the mqtt broker in A-MQ

2016-10-24 03:20 UTC, sabre1041 commented on iot-ose(2).json
> +﻿{"paragraphs":[{"title":"Counter Readings","text":"%psql\n\nselect initcap(data_type), payload, time_stamp from measure where data_type != 'gps';","dateUpdated":"2016-10-02T07:37:00-0500","config":{
I updated/reduced the content in my latest [PR](https://github.com/sabre1041/iot-ose/pull/10)

2016-10-25 00:34 UTC, ishuverma commented on README.adoc
> +image:images/ose-iot.png[width="500", height="400", align="center"]
yes, how does this one look
![iot-ose-picture](https://cloud.githubusercontent.com/assets/16406768/19668931/1eb2c82e-9a10-11e6-9d50-f515bfcc8086.png)

2016-11-02 06:28 UTC, closed without merging